name: Generate Static Comments

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM UTC

jobs:
  build-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch approved comments from Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node build/buildBlogComments.js

      - name: Commit and push updated comment files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "Jeremy Huff"
          git config user.email "jeremythuff@gmail.com"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}
          git add blog/posts/*
          git diff --cached --quiet || git commit -m "Update post-commits"
          git log -1
          git push origin HEAD:${{ github.ref_name }}
          